### ISSUE TITLE
The number of carriers has dropped below 100, is that okay?

### ISSUE THREAD

**Issue by Peter-Liska** [Zasilkovna/prestashop#156]
After the last update of carriers, the number of carriers dropped rapidly, is that okay?

**Comment by MatyasKoval** [comment]
Hello, can You please tell us how many cariers can You currently see? 
Since version 2.1.11 the list does not contain pickup points anymore, since pickup points are kept updated by the widget and therefore having them included in this list was obsolete, 
As of now, the list contains only carriers and therefore the number is a lot lower.
If You see the number to be around 90, everything is in order. If the number differs more prominently, please write to us at technicka.podpora@zasilkovna.cz with a screenshot and more information.

**Comment by Peter-Liska** [comment]
Thank you for your answer. Then it's okay.

Because there were thousands of them in the past.
